export {
  calculateInterimSalary,
  computeMissionGrossFromHours,
  computeIfmAmount,
  computeIccpAmount,
  estimateInterimNet,
  parseInterimNumber,
  validateIfmRatePercent,
  validateIccpRatePercent,
  INTERIM_DEFAULT_IFM_RATE_PERCENT,
  INTERIM_DEFAULT_ICCP_RATE_PERCENT,
  INTERIM_MIN_IFM_RATE_PERCENT,
  INTERIM_GENERAL_IFM_RATE_PERCENT,
  INTERIM_MIN_ICCP_RATE_PERCENT,
  INTERIM_DEFAULT_PROFILE,
  type InterimCalculationInput,
  type InterimCalculationResult,
  type InterimInputMode,
} from "./engine";

export {
  INTERIM_PATH,
  INTERIM_SLUG,
  INTERIM_H1,
  INTERIM_SEO_TITLE,
  INTERIM_META_DESCRIPTION,
  INTERIM_BREADCRUMB,
  INTERIM_SUBTITLE,
  INTERIM_FRESHNESS_LINE,
  INTERIM_SOURCES,
  INTERIM_IFM_EXCEPTIONS,
  INTERIM_NET_DISCLAIMER,
  INTERIM_HS_NET_WARNING,
  INTERIM_SCOPE_DISCLAIMER,
  INTERIM_SMIC_MONTHLY_FORMULA_NOTE,
  INTERIM_DEFAULT_MISSION_GROSS,
  INTERIM_PUBLISHED_AT,
  INTERIM_UPDATED_AT,
  INTERIM_UPDATED_AT_LABEL,
  INTERIM_RULES_VERIFIED_LABEL,
  formatEuro,
  formatEuroApprox,
  formatEuroApproxWord,
  buildInterimCopySummary,
  buildInterimCopyDetail,
  SMIC_CURRENT,
  SMIC_LABELS,
} from "./data";

/** Composant client : importer depuis `./InterimSalaryCalculator` (évite le JSX dans les tests). */
